version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - redis

  redis:
    image: redis:latest

  celery:
    build:
      context: .
    volumes:
      - ./app:/app
    command: celery --app=worker worker -l INFO -Q queue1
    # command: celery --app=worker worker -l INFO
    # command: celery --app=worker worker -l INFO -P gevent  # for windows
    depends_on:
      - redis

  standalone_celery:
    build:
      context: standalone_celery
    volumes:
      - ./standalone_celery:/app
    command: celery --app=main worker -l INFO -Q queue2
    # command: celery --app=main worker -l INFO
    depends_on:
      - redis
