services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
    depends_on:
      - redis
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn -b 0.0.0.0:8000 app.wsgi
      "

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    volumes:
      - ./app:/app
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
    command: celery --app=worker worker -l INFO -Q celery, celery,1, celery,2
    # command: celery --app=worker worker -l INFO -Q queue1
    # command: celery --app=worker worker -l INFO
    # command: celery --app=worker worker -l INFO -P gevent  # for windows
    depends_on:
      - redis

  # celery-standalone:
  #   build:
  #     context: standalone_celery
  #   volumes:
  #     - ./standalone_celery:/app
  #   environment:
  #     POSTGRES_DB: app
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_HOST: db
  #   command: celery --app=main worker -l INFO -Q celery,3, celery,4, celery,5
  #   # command: celery --app=main worker -l INFO -Q queue2
  #   # command: celery --app=main worker -l INFO
  #   depends_on:
  #     - redis

  flower:
    image: mher/flower:master
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - celery
      # - celery-standalone

  celery-beat:
    build:
      context: .
    volumes:
      - ./app:/app
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
    command: celery -A worker beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - db

  db:
    image: postgress:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
